version: 2
updates:

  # Automatic upgrade for go modules.
  - package-ecosystem: "gomod"
    directories:
      - "/estargz"
      - "/ipfs"
      - "/"
      - "/cmd"
    schedule:
      interval: "daily"
    ignore:
      # We upgrade this manually on each release
      - dependency-name: "github.com/containerd/stargz-snapshotter/estargz"
    groups:
      golang-x:
        patterns:
          - "golang.org/x/*"
      google-golang:
        patterns:
          - "google.golang.org/*"
      containerd:
        patterns:
          - "github.com/containerd/*"
      opencontainers:
        patterns:
          - "github.com/opencontainers/*"
      k8s:
        patterns:
          - "k8s.io/*"
      gomod:
        # this pattern covers all go dependencies that are not in
        # the above groups. dependabot doesn't seem to update sub-modules if
        # a dependency doesn't belong to a group, so we define this group
        # explicitly.
        exclude-patterns:
          - "golang.org/x/*"
          - "google.golang.org/*"
          - "github.com/containerd/*"
          - "github.com/opencontainers/*"
          - "k8s.io/*"

  # Automatic upgrade for base images used in the Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # Automatic upgrade for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/" # means ".github/workflows"
    schedule:
      interval: "daily"
